### ISSUE TITLE
ImportError: cannot import name 'main' from 'ghp_import'

### ISSUE THREAD

**Issue by vhsven** [getnikola/nikola-action#4]
Since about a day ago, the Github Action builds of my nikola blog are failing with `ImportError: cannot import name 'main' from 'ghp_import'`. Rebuilding a commit that worked before also results in failure now, so something outside my code changed. Background info: I'm using my own requirements.txt file, so the action runs `pip install -r requirements.txt ghp-import2` from entrypoint.sh at some point during setup.

When comparing the logs of two runs on the same commit (one that worked and one that does not), I noticed the docker layer IDs changed. Turns out image `python:3.8` points to `python:3.8.13` instead of `python:3.8:12` since a couple of days. The latter ships with pip version 22 instead of version 21.

I managed to reproduce and narrow down the problem as follows.

```bash
$ docker run -it --rm python:3.8.12 /bin/bash
# pip install nikola[extras]==8.* ghp-import2
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
# ghp-import -h
Usage: ghp-import [OPTIONS] DIRECTORY

Options:
  -n          Include a .nojekyll file in the branch.
  -m MESG     The commit message to use on the target branch.
  -p          Push the branch to origin/{branch} after committing.
  -r REMOTE   The name of the remote to push to. [origin]
  -b BRANCH   Name of the branch to write to. [gh-pages]
  -h, --help  show this help message and exit

# pip freeze | grep ghp
ghp-import==2.0.2
ghp-import2==1.0.1
```

This works fine and shows the helptext of ghp-import2. We can also see that both ghp-import (via Nikola extras) and ghp-import2 are installed but they don't seem to conflict with one another. The latter simply seems to shadow the former.

Similar test with the latest version:

```bash
$ docker run -it --rm python:3.8.13 /bin/bash
# pip install nikola[extras] ghp-import2
# ghp-import -h
Traceback (most recent call last):
  File "/usr/local/bin/ghp-import", line 5, in <module>
    from ghp_import import main
ImportError: cannot import name 'main' from 'ghp_import' (/usr/local/lib/python3.8/site-packages/ghp_import/__init__.py)

# pip freeze | grep ghp
ghp-import==2.0.2
ghp-import2==1.0.1
```

This reproduces the error I encounter in my Github Action. Both packages are still installed, but now they seem to be conflicting with one another. I cannot pinpoint exactly what changed, but the upgrade from pip version 21 to pip version 22 is definitely somewhere at the heart of this.

Looking at the source code of ghp-import and ghp-import2, they only seem loosely inspired by one another. I fail to understand why anyone would want to install both. ghp-import seems more actively maintained and offers more options. Unfortunately this GitHub Action is forcing the installation of ghp-import2 no matter what I write in my requirements.txt file.

With `ghp-import2` omitted from the pip install line, the error disappears:

```bash
$ docker run -it --rm python:3.8.13 /bin/bash
# pip install nikola[extras]
# ghp-import -h
Usage: ghp-import [OPTIONS] DIRECTORY

Options:
  -n, --no-jekyll       Include a .nojekyll file in the branch.
  -c CNAME, --cname=CNAME
                        Write a CNAME file with the given CNAME.
  -m MESG, --message=MESG
                        The commit message to use on the target branch.
  -p, --push            Push the branch to origin/{branch} after committing.
  -x PREFIX, --prefix=PREFIX
                        The prefix to add to each file that gets pushed to the
                        remote. Only files below this prefix will be cleared
                        out. [none]
  -f, --force           Force the push to the repository.
  -o, --no-history      Force new commit without parent history.
  -r REMOTE, --remote=REMOTE
                        The name of the remote to push to. [origin]
  -b BRANCH, --branch=BRANCH
                        Name of the branch to write to. [gh-pages]
  -s, --shell           Use the shell when invoking Git. [False]
  -l, --follow-links    Follow symlinks when adding files. [False]
  --version             show program's version number and exit
  -h, --help            show this help message and exit
# pip freeze | grep ghp
ghp-import==2.0.2
```

Note that I reduced my setup to its essence in the code above to analyze this issue. In practise I need more packages so it is not an option for me to simply omit the requirements.txt file.

I only verified that this would solve the initial `ghp-import -h` call where my problem is happening right now. I have not tested whether the rest of the action is actually compatible with `ghp-import` instead of `ghp-import2`. Judging by <https://github.com/getnikola/nikola/blob/09fb875ca87e94e2579f0559f5799c048ae6499f/nikola/plugins/command/github_deploy.py#L163> (`command = ['ghp-import', '-n', '-m', commit_message, '-p', '-r', remote, '-b', deploy, output_folder]`) it seems compatible with both. Since the nikola extras explicitly point to `ghp-import` and some people probably just deploy from the command line without using this action, my guess is that it will be OK.

Conclusion:

I image this problem is going to affect all your users that ship their own requirements.txt file from now on.

Please replace line `pip install -r requirements.txt ghp-import2` with `pip install -r requirements.txt` or `pip install -r requirements.txt ghp-import`. I obviously prefer the former because full control should really mean full control.

**Comment by Kwpolska** [comment]
Use of `ghp-import` is mandatory for the action, but not necessarily for local usage of the repo. I replaced the line with `pip install -r requirements.txt ghp-import` and also bumped the Python image to 3.10.
