### ISSUE TITLE
Use of filters in conf.py breaks Action startup

### ISSUE THREAD

**Issue by gwax** [getnikola/nikola-action#5]
1. `conf.py` is imported: https://github.com/getnikola/nikola-action/blob/master/entrypoint.sh#L12
2. Before nikola is installed: https://github.com/getnikola/nikola-action/blob/master/entrypoint.sh#L30
3. Recommended filters require import of nikola: https://github.com/getnikola/nikola/blob/master/nikola/conf.py.in#L637

So trying to use the action with filters in `conf.py` results in an import error:
```
==> Preparing...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/github/workspace/conf.py", line 7, in <module>
    from nikola import filters
ModuleNotFoundError: No module named 'nikola'
```

**Comment by Kwpolska** [comment]
Since having FILTERS at this step isn’t critical, I’d solve this with the following change to `conf.py` for sites using the Action:

```
try:
    from nikola import filters
    FILTERS = {
       ".html": [filters.typogrify],
       ".js": [filters.closure_compiler],
       ".jpg": ["jpegoptim --strip-all -m75 -v %s"],
    }
except ImportError:
    FILTERS = {}
```

**Comment by Kwpolska** [comment]
I added the above sample under a _Caveats_ section in `README.md`.
