### ISSUE TITLE
Conflict between this action (pushing to gh-pages) and github-pages bot?

### ISSUE THREAD

**Issue by eudoxos** [getnikola/nikola-action#8]
Whenever I make a push to the repo, both nikola-action and the github-pages bot get run, despite having `.nojekyll` file in the main (source) branch which is correctly copied to the `gh-pages` branch. Is that a problem with this action? How can it be fixed? Do I have some other problem in my setup?

The workflow file is very plain, here: https://github.com/eudoxos/brzdime/blob/main/.github/workflows/main.yml

This is how both action are always triggered:

![image](https://user-images.githubusercontent.com/1029876/203093988-86086dd1-dcc5-480a-8367-581b0574a7fe.png)

These are the settings: 

![image](https://user-images.githubusercontent.com/1029876/203094407-bbf5f805-145d-4c4b-9e37-21a6ef5ee277.png)

Any ideas what is up?

**Comment by Kwpolska** [comment]
This seems to be the correct behavior. The deployment of a branch to GitHub Pages seems to happen as an action nowadays. There seems to be a way to deploy directly from a GitHub Action, but it’s in beta.

Are you experiencing any issues with the deployment?

**Comment by eudoxos** [comment]
Okay, I understand now. The build action would be deleting `CNAME` in the `gh-pages` branch, and since GitHub keeps the hosting domain setting in there, the setting would be reset after each rebuild and the website disappeared.

The solution was to put both `CNAME` and `.nojekyll` into `files/` so that they appear in `output/` and are commited to `gh-pages`.

Perhaps a documentation tip?

Thank you for your work on Nikola and everything else!
